### ISSUE TITLE
UI: Improvement in the UI of the form in NFT making 

### ISSUE THREAD

**Issue by dhruvsol** [cosmoinfinitas/Cosmo_NFT_Market#5]
### Description

Need some imporvement in UI in the create  items page 

### Domain

UI/UX

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Gurdeep475** [comment]
hey, i would like to work on this issue under GSSOC`22

**Comment by dhruvsol** [comment]
@Gurdeep475  i have assign u the issue. If u face any issue ping me on discord :smile:
