### ISSUE TITLE
UI: Improvement in the UI of Dashboard page

### ISSUE THREAD

**Issue by dhruvsol** [cosmoinfinitas/Cosmo_NFT_Market#6]
### Description

change the UI of Dashborad of UI page

### Domain

UI/UX

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by itsharshitb** [comment]
I will try to make the UI of the form better. Please assign me this issue.

**Comment by dhruvsol** [comment]
> I will try to make the UI of the form better. Please assign me this issue.

Assign u the issue . For level 2 issue the time limit is 4-5 days if u require more time Please contact me & If u face any issue feel free to ping me anytime for help
